spring:
  application:
    name: config-server
  cloud:
    discovery:      enabled: true    config:      server:        git:          uri: https://github.com/anupamatrey/service-configuration.git          clone-on-start: true
server:  port: 8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: https://eureka-1216.herokuapp.com/eureka/